### ISSUE TITLE
Need good outputs

### ISSUE THREAD

**Issue by dpinney** [lanl-ansi/gfm-lpnorm#4]
Right now the model outputs:

1. USER_PROVIDED_NAME is the full input to RDT
2. RDT-to-Poles.json LOGGING FILE, estimate of where the poles are generated synthetically. 3. 3. 3. FRAGILITY_ResponseEstimators.json LOGGING FILE, shows where the actual damage.

Requested changes:
1. Only generate logging files when they are requested.
2. Let the user choose the logging file names. Multiple runs of the program = logging files clobber each other.

**Comment by rb004f** [comment]
Done
