### ISSUE TITLE
Show disabled loads as part of GFM output

### ISSUE THREAD

**Issue by dpinney** [lanl-ansi/gfm-lpnorm#9]
Is it possible to list the loads that were lost in the GFM output?

This would simplify post-run analysis.

If this isn't possible inside GFM, it's something that could be done elsewhere (i.e. by comparing damaged lines from GFM to source circuit model).

**Comment by rb004f** [comment]
This is an output produced by RDT. We will move this discussion over there.

**Comment by dpinney** [comment]
Sounds great. Thanks.
